### ISSUE TITLE
Demo video looks great but code does fail with a js error after login

### ISSUE THREAD

**Issue by ddengler** [chrismccord/todo_trek#2]
Just wanted to check this out during my lunch break. I run into the following js error after login:

```
dom_patch.js:103 Uncaught TypeError: deleteIds.forEach is not a function
    at dom_patch.js:103:19
    at Set.forEach (<anonymous>)
    at dom_patch.js:101:20
    at LiveSocket.time (live_socket.js:253:59)
    at DOMPatch.perform (dom_patch.js:100:16)
    at View.performPatch (view.js:405:11)
    at View.applyJoinPatch (view.js:331:10)
    at View.onJoinComplete (view.js:308:14)
    at view.js:272:14
    at View.applyDiff (view.js:241:5)
```

I updated all dependencies just to see if it changes anything. It does not. Sadly I do not have the time right now to investigate this any further. Just wanted to let you @chrismccord  know right away, given the related blog post.

**Comment by ddengler** [comment]
No clue why, but it was fixed by a hard reload without caching – at least on my computer with all dependencies now updated.
